### ISSUE TITLE
UI flow

### ISSUE THREAD

**Issue by ymhuang0808** [OpenISDM/madapp#8]
We need a perfect MAD UI flow.

**Comment by JimJimlin** [comment]
We already have a UI flow prototype now.
We need divide and conquer some tasks are below:
1. Initial page
2. Map view
3. Show shelter information on MAP view
4. Setting
5. Pin location
6. Pinned history
7. Notification

**Comment by JimJimlin** [comment]
Here is the UI ↓
[MadApp_UI flow](https://drive.google.com/file/d/0BxLSsjV6sZ2PNVZydzljM1l5S2M/view?usp=sharing).
